routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

Route::get('/search', 'HomeController@search')->name('search');

Route::get('/{title}/{id}', 'ArticleController@show')->name('article.show')->where('id', '\d+');

Route::get('/category/{name}/{id}', 'CategoryController@show')->name('category.show')->where('id', '\d+');


Route::get('settings', 'HomeController@settings')->middleware('auth')->name('settings');
Route::post('settings', 'HomeController@settings')->middleware('auth');




Route::post('/comment/{id}', 'ArticleController@comment')
    ->name('comment.store')
    ->where('id', '\d+')
    ->middleware('auth');

//Google auth
Route::get('/login/google/redirect', 'Auth\GoogleController@redirect')->name('login.google.redirect');
Route::get('/login/google/handle', 'Auth\GoogleController@handle')->name('login.google.handle');


Route::group(['middleware' => 'admin', 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('image/upload', 'HomeController@upload')->name('image.upload');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@store')->name('settings.store');

    Route::resource('user', 'UserController');
    Route::resource('article', 'ArticleController');
    Route::resource('category', 'CategoryController');
});

app/Models/Article.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Storage;

class Article extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'category_id',
        'user_id',

        'name',
        'description',
        'image',
        'content',
        'views',
        'published_at',
        'published'
    ];

    protected $dates = [
      'published_at'
    ];


    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getImageAttribute($value)
    {
        if ($value) {
            return  Storage::url('article/image/' . $value);
        } else {
            return null;
        }
    }

    public function setImageAttribute($value)
    {
        if ($value) {
            $name = str_slug($this->name) . '_' . uniqid() . '.' . $value->getClientOriginalExtension();
            $storage = Storage::disk('public')->putFileAs('article/image',  $value, $name);
            if ($storage) {
                $this->attributes['image'] = $name;
            }
        }
    }

    public function scopeIsPublished($query)
    {
        return $query->where('published', true)->where('published_at', '<', Carbon::now());
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Storage;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("admin.article.index", ['articles' => Article::paginate(20)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.article.create", ['article' => new Article()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        $article = new Article();

        $article->name = $request->get('name');
        $article->category_id = $request->get('category_id');
        $article->user_id = $request->get('user_id');
        $article->description = $request->get('description');
        $article->image = $request->file('image');
        $article->content = $request->get('content');

        $article->published_at = $request->get('submit') == 'publish' ? Carbon::now() : null;

        $article->published = $request->get('submit') == 'publish' ? true : false;

        $article->save();

        if ($request->get('submit') == 'save') {
            return redirect()->route('admin.article.edit', ['article' => $article]);
        }
        return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::findOrFail($id);

        return view('admin.article.edit', ['article' => $article]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, $id)
    {
        $article = Article::findOrFail($id);

        $article->name = $request->get('name');
        $article->category_id = $request->get('category_id');
        $article->user_id = $request->get('user_id');
        $article->description = $request->get('description');
        $article->image = $request->file('image');
        $article->content = $request->get('content');

        switch ($request->get('submit')) {
            case 'publish':
                $article->published_at = Carbon::now();
                if (!$article->image) {
                    $this->validate($request, [
                        'image' => 'required|image'
                    ]);
                }
                $article->published = true;
                break;
            case 'unpublish':
                $article->published = false;
                break;
        }

        $article->save();

        if ($request->get('submit') == 'save') {
            return redirect()->route('admin.article.edit', ['article' => $article]);
        }

        return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::findOrFail($id);

        $article->delete();

        return redirect()->route('admin.article.index');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function show($title, $id)
    {
        $article = Article::findOrFail($id);

        $article->increment('views');

        return view('article.show', [
           'article' => $article
        ]);
    }

    public function comment(Request $request, $id)
    {
        $article = Article::findOrFail($id);


        $this->validate($request, [
            'comment' => 'required'
        ]);

        $article->comments()->create([
            'content' => $request->get('comment'),
            'user_id' => auth()->user()->id
        ]);

        return redirect()->back();
    }
}

resources/views/admin/article/_layout.blade.php
@extends('layouts.admin')

@section('admin')
    <div class="row">
        <div class="col-md-9">
            <h3>Article <small> @yield('type') </small></h3>
        </div>
        <div class="col-md-3">
            <a href="{{ route('admin.article.create') }}" type="button" class="btn btn-primary">Create new article ?</a>
        </div>
    </div>
    @yield('article')
@endsection

resources/views/admin/article/create.blade.php
@extends('admin.article._layout')

@section('article')
    <div class="panel panel-default">
        <div class="panel-body">
            @include('admin.article.form', ['model' => $article, 'method' => 'POST', 'url' => route('admin.article.store')])
        </div>
    </div>
@endsection

@section('type', 'Create')

resources/views/admin/article/edit.blade.php
@extends('admin.article._layout')

@section('article')
    <div class="panel panel-default">
        <div class="panel-body">
            @include('admin.article.form', ['model' => $article, 'method' => 'PUT', 'url' => route('admin.article.update', ['article' => $article])])
        </div>
    </div>
@endsection

@section('type', 'Edit')

resources/views/admin/article/form.blade.php
@include('components.errors')
{{ Form::model($model,['url' => $url, 'method' => $method, 'enctype' => 'multipart/form-data']) }}

<div class="form-group">
    {{ Form::label('name', 'Title (required)') }}
    {{ Form::text('name', null, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('description', 'Description') }}
    {{ Form::textarea('description', null, ['class' => 'form-control', 'rows' => 4]) }}
</div>
<div class="form-group">
    {{ Form::label('content', 'Content') }}
    <div id="content">
        {{ $model->content }}
    </div>
</div>
<div class="form-group">
    <div class="row">
        <div class="col-xs-4">
            {{ Form::label('category_id', 'Category') }}
            {{ Form::select('category_id', App\Models\Category::get()->pluck('name' ,'id')->all() , null, ['placeholder' => 'Pick a category (or not)', 'class' => 'form-control']) }}
        </div>
        <div class="col-xs-4">
            {{ Form::label('user_id', 'Author') }}
            {{ Form::select('user_id',  App\Models\User::where('admin', true)->get()->pluck('name' ,'id')->all() , auth()->user()->id, ['class' => 'form-control']) }}
        </div>
        <div class="col-xs-4">
            {{ Form::label('image', 'Image') }}
            {{ Form::file('image') }}
            <div class="help-block">Format: 750 x 300</div>
            @if($model->image)
                <button class="btn btn-primary btn-xs btn-block" type="button" data-toggle="collapse"
                        data-target="#collapseImage" aria-expanded="false" aria-controls="collapseExample">
                    Display image
                </button>
                <div class="collapse" id="collapseImage">
                    <div class="well">
                        <img width="100%" src="{{ $model->image }}">
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>

<div class="form-group">
    <div class="row">
        <div class="col-xs-8">
            {{ Form::button('Save', ['class' => 'btn-primary btn-block', 'name' => 'submit',  'type' => 'submit', 'value' => 'save']) }}
        </div>
        <div class="col-xs-4">
            @if ($model->published)
                {{ Form::button('Unpublish', ['class' => 'btn-danger btn-block', 'name' => 'submit', 'type' => 'submit', 'value' => 'unpublish']) }}
            @else
                {{ Form::button('Publish', ['class' => 'btn-warning btn-block', 'name' => 'submit',  'type' => 'submit', 'value' => 'publish']) }}
            @endif
        </div>

    </div>
</div>
{{ Form::close() }}

resources/views/admin/article/index.blade.php
@extends('admin.article._layout')

@section('article')
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <td>#</td>
                    <td>Name</td>
                    <td>Author</td>
                    <td class="text-center">Views</td>
                    <td class="text-center">Published</td>
                    <td class="text-center">Actions</td>
                </tr>
                </thead>
                <tbody>
                @foreach($articles as $article)
                    <tr>
                        <td>{{ $article->id }}</td>
                        <td>{{ $article->name }}</td>
                        <td>{{ $article->user->name }}</td>
                        <td class="text-center">{{ $article->views }}</td>
                        <td class="text-center">
                            @if($article->published)
                                <span class="glyphicon glyphicon-ok"></span>
                            @else
                                <span class="glyphicon glyphicon-remove"></span>
                            @endif
                        </td>
                        <td class="text-center">
                            <a href="{{ route('admin.article.edit', ['article' => $article]) }}"
                               class="btn btn-default btn-xs">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </a>
                            <button type="button" class="btn btn-xs btn-default" data-toggle="modal" data-target="#rm-{{$article->id}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                            <div id="rm-{{ $article->id }}" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content">
                                        {{ Form::open(['url' => route('admin.article.destroy', ['article' => $article->id]), 'method' => 'delete']) }}
                                            {{ Form::button('Delete', ['type' => 'submit', 'class' => 'btn btn-block btn-danger']) }}
                                        {{ Form::close() }}
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $articles->links() }}
        </div>
    </div>
@endsection