routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

Route::get('/search', 'HomeController@search')->name('search');

Route::get('/{title}/{id}', 'ArticleController@show')->name('article.show')->where('id', '\d+');

Route::get('/category/{name}/{id}', 'CategoryController@show')->name('category.show')->where('id', '\d+');


Route::get('settings', 'HomeController@settings')->middleware('auth')->name('settings');
Route::post('settings', 'HomeController@settings')->middleware('auth');




Route::post('/comment/{id}', 'ArticleController@comment')
    ->name('comment.store')
    ->where('id', '\d+')
    ->middleware('auth');

//Google auth
Route::get('/login/google/redirect', 'Auth\GoogleController@redirect')->name('login.google.redirect');
Route::get('/login/google/handle', 'Auth\GoogleController@handle')->name('login.google.handle');


Route::group(['middleware' => 'admin', 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('image/upload', 'HomeController@upload')->name('image.upload');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@store')->name('settings.store');

    Route::resource('user', 'UserController');
    Route::resource('article', 'ArticleController');
    Route::resource('category', 'CategoryController');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name',
        'description',

        'navbar_display',
        'navbar_name',

        'order'
    ];

    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("admin.category.index", ['categories' => Category::paginate(20)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.category.create", ['category' => new Category()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        Category::create([
            'name' => $request->get('name'),
            'navbar_name' => $request->get('navbar_name') ? $request->get('navbar_name') : $request->get('name'),
            'description' => $request->get('description'),
            'order' => $request->get('order')
        ]);

        return redirect()->route('admin.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view('admin.category.edit', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        $category = Category::findOrFail($id);

        $category->name = $request->get('name');
        $category->navbar_name = $request->get('navbar_name') ? $request->get('navbar_name') : $request->get('name');

        $category->navbar_display = $request->get('navbar_display') && $request->get('navbar_display') === 'on' ? true : false;
        $category->description = $request->get('description');

        $category->order =  $request->get('order');

        $category->save();
        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        return redirect()->route('admin.category.index');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function show( $name, $id)
    {
        $category = Category::findOrFail($id);

        return view('category', [
            'category' => $category,
            'articles' => $category->articles()->IsPublished()->orderBy('published_at', 'DESC')->paginate(9)
        ]);
    }
}

resources/views/admin/category/_layout.blade.php
@extends('layouts.admin')

@section('admin')
    <div class="row">
        <div class="col-md-9">
            <h3>Category <small> @yield('type') </small></h3>
        </div>
    </div>
    @yield('category')
@endsection

resources/views/admin/category/create.blade.php
@extends('admin.category._layout')

@section('category')
    <div class="panel panel-default">
        <div class="panel-body">
            @include('admin.category.form', ['model' => $category, 'method' => 'POST', 'url' => route('admin.category.store')])
        </div>
    </div>
@endsection

@section('type', 'Create')

resources/views/admin/category/edit.blade.php
@extends('admin.category._layout')

@section('category')
    <div class="panel panel-default">
        <div class="panel-body">
            @include('admin.category.form', ['model' => $category, 'method' => 'PUT', 'url' => route('admin.category.update', ['category' => $category])])
        </div>
    </div>
@endsection

@section('type', 'Edit')

resources/views/admin/category/form.blade.php
@include('components.errors')
{{ Form::model($model,['url' => $url, 'method' => $method]) }}

<div class="form-group">
    {{ Form::label('name', 'Name') }}
    {{ Form::text('name', null, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('navbar_name', 'Navbar name') }}
    {{ Form::text('navbar_name', null, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::label('description', 'Description') }}
    {{ Form::textarea('description', null, ['class' => 'form-control', 'rows' => 2]) }}
</div>
<div class="form-group">
    {{ Form::checkbox('navbar_display', null) }}
    {{ Form::label('navbar_display', 'Display on navbar ?') }}
</div>
<div class="form-group">
    {{ Form::label('order', 'Navbar order') }}
    {{ Form::number('order', 0, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::submit('Save',['class' => 'btn-primary btn-block']) }}
</div>
{{ Form::close() }}

resources/views/admin/category/index.blade.php
@extends('admin.category._layout')

@section('category')
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <td>#</td>
                    <td>Name</td>
                    <td><a href="{{ route('admin.category.create') }}" class="btn btn-success btn-xs pull-right">
                            Add category <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>{{ $category->id }}</td>
                        <td>{{ $category->name }}</td>
                        <td>
                            <div class="pull-right">
                                <a href="{{ route('admin.category.edit', ['category' => $category]) }}"
                                   class="btn btn-default btn-xs">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                </a>
                                <button type="button" class="btn btn-xs btn-default" data-toggle="modal"
                                        data-target="#rm-{{$category->id}}"><span class="glyphicon glyphicon-remove"
                                                                                  aria-hidden="true"></span></button>
                                <div id="rm-{{ $category->id }}" class="modal fade bs-example-modal-sm" tabindex="-1"
                                     role="dialog" aria-labelledby="mySmallModalLabel">
                                    <div class="modal-dialog modal-sm" role="document">
                                        <div class="modal-content">
                                            {{ Form::open(['url' => route('admin.category.destroy', ['category' => $category]), 'method' => 'DELETE', 'class' => '']) }}
                                            {{ Form::button('Delete', ['type' => 'submit', 'class' => 'btn btn-block btn-danger']) }}
                                            {{ Form::close() }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $categories->links() }}
        </div>
    </div>
@endsection