routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

Route::get('/search', 'HomeController@search')->name('search');

Route::get('/{title}/{id}', 'ArticleController@show')->name('article.show')->where('id', '\d+');

Route::get('/category/{name}/{id}', 'CategoryController@show')->name('category.show')->where('id', '\d+');


Route::get('settings', 'HomeController@settings')->middleware('auth')->name('settings');
Route::post('settings', 'HomeController@settings')->middleware('auth');




Route::post('/comment/{id}', 'ArticleController@comment')
    ->name('comment.store')
    ->where('id', '\d+')
    ->middleware('auth');

//Google auth
Route::get('/login/google/redirect', 'Auth\GoogleController@redirect')->name('login.google.redirect');
Route::get('/login/google/handle', 'Auth\GoogleController@handle')->name('login.google.handle');


Route::group(['middleware' => 'admin', 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('image/upload', 'HomeController@upload')->name('image.upload');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@store')->name('settings.store');

    Route::resource('user', 'UserController');
    Route::resource('article', 'ArticleController');
    Route::resource('category', 'CategoryController');
});

resources/views/partials/footer.blade.php
<footer>
    <div class="container">
        <div class="row">
            @if($categories->count())
                <div class="col-md-2">
                    <h3> @lang('main.footer.category') </h3>
                    <ul>
                        @foreach($categories as $category)
                            <li>
                                <a href="{{ route('category.show', ['name' => str_slug($category->name), 'id' => $category->id]) }}"> {{ $category->name }} </a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="col-md-2">
                @if (Settings::get('social_facebook') || Settings::get('social_youtube') || Settings::get('social_twitter') || Settings::get('social_instagram') || Settings::get('social_linkedIn'))
                    <h3> @lang('main.footer.social')</h3>
                    <ul>
                        @if(Settings::get('social_facebook'))
                            <li>
                                <a target="_blank" href="{{ Settings::get('social_facebook') }}"><i
                                            class="fa fa-facebook fa-fw"></i>Facebook</a>
                            </li>
                        @endif
                        @if(Settings::get('social_youtube'))
                            <li>
                                <a target="_blank" href="{{ Settings::get('social_facebook') }}"><i
                                            class="fa fa-youtube fa-fw"></i>Youtube</a>
                            </li>
                        @endif
                        @if(Settings::get('social_twitter'))
                            <li>
                                <a target="_blank" href="{{ Settings::get('social_twitter') }}"><i
                                            class="fa fa-twitter fa-fw"></i>Twitter</a>
                            </li>
                        @endif
                        @if(Settings::get('social_instagram'))
                            <li>
                                <a target="_blank" href="{{ Settings::get('social_instagram') }}"><i
                                            class="fa fa-instagram fa-fw"></i>Instagram</a>
                            </li>
                        @endif
                        @if(Settings::get('social_linkedIn'))
                            <li>
                                <a target="_blank" href="{{ Settings::get('social_linkedIn') }}"><i
                                            class="fa fa-linkedin fa-fw"></i>LinkedIn</a>
                            </li>
                        @endif
                    </ul>
                @endif

            </div>
            <div class="col-md-8">
                <h3> @lang('main.footer.about') </h3>
                <p>
                    {{ Settings::get('footer_content') }}
                </p>
            </div>
        </div>
    </div>
</footer>

resources/views/partials/header.blade.php
<nav class="navbar navbar-default navbar-static-top navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ route('home') }}">
                @if (Storage::disk('public')->exists('settings/logo.png'))
                    <img class="logo" style="display: inline" src="{{ asset('storage/settings/logo.png') }}"> @endif
                    {{ Settings::get('app_name') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                &nbsp;@foreach($categories as $category)
                    <li>
                        <a href="{{ route('category.show', ['name' => str_slug($category->name), 'id' => $category->id]) }}">
                            {{ $category->navbar_name }}
                        </a>
                    </li>
                @endforeach
            </ul>
            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @if (Auth::guest())
                    <li><a href="{{ route('login') }}"> @lang('main.header.login') / @lang('main.header.register') </a></li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li>
                            @if (auth()->user()->admin)
                                <li>
                                    <a href="{{ route('admin.home') }}">Admin</a>
                                </li>
                            @endif
                            <li>
                                <a href="{{ route('settings') }}">@lang('main.header.settings')</a>
                            </li>
                            <li>

                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    @lang('main.header.logout')
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endif
            </ul>
            <form method="get" action="{{ route('search') }}" class="navbar-form navbar-right">
                {{ csrf_field() }}
                <div class="form-group">
                    <input type="text" name="query" class="form-control" placeholder="@lang('main.header.search')">
                </div>
            </form>
        </div>
    </div>
</nav>

resources/views/partials/sidebar.blade.php
<div class="list-group">
    <a href="{{ route('admin.home') }}" class="list-group-item @active('admin/home/?.*') ">Home</a>
    <a href="{{ route('admin.settings.index') }}" class="list-group-item @active('admin/settings/?.*') ">Settings</a>
</div>

<div class="list-group">
    <a href="{{ route('admin.user.index') }}" class="list-group-item @active('admin/user/?.*') ">Users</a>
    <a href="{{ route('admin.article.index') }}" class="list-group-item @active('admin/article/?.*') ">Articles</a>
    <a href="{{ route('admin.category.index') }}" class="list-group-item @active('admin/category/?.*') ">Categories</a>
</div>