routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

Route::get('/search', 'HomeController@search')->name('search');

Route::get('/{title}/{id}', 'ArticleController@show')->name('article.show')->where('id', '\d+');

Route::get('/category/{name}/{id}', 'CategoryController@show')->name('category.show')->where('id', '\d+');


Route::get('settings', 'HomeController@settings')->middleware('auth')->name('settings');
Route::post('settings', 'HomeController@settings')->middleware('auth');




Route::post('/comment/{id}', 'ArticleController@comment')
    ->name('comment.store')
    ->where('id', '\d+')
    ->middleware('auth');

//Google auth
Route::get('/login/google/redirect', 'Auth\GoogleController@redirect')->name('login.google.redirect');
Route::get('/login/google/handle', 'Auth\GoogleController@handle')->name('login.google.handle');


Route::group(['middleware' => 'admin', 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('image/upload', 'HomeController@upload')->name('image.upload');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@store')->name('settings.store');

    Route::resource('user', 'UserController');
    Route::resource('article', 'ArticleController');
    Route::resource('category', 'CategoryController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'google_id',
        'email',
        'avatar',
        'password',
        'admin',
        'banned'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getAvatarAttribute($value)
    {
        if (!$value) {
            $value = 'https://www.gravatar.com/avatar/' . md5(strtolower($this->email)) . '?s=180';
        }
        return $value;
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("admin.user.index", ['users' => User::paginate(20)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        $user = User::findOrFail($id);

        $user->name = $request->get('name');
        $user->email = $request->get('email');

        $user->admin = $request->get('admin') && $request->get('admin') === 'on' ? true : false;
        $user->banned = $request->get('banned') && $request->get('banned') === 'on' ? true : false;

        $user->save();

        return redirect()->route('admin.user.edit', ['user' => $user]);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/_layout.blade.php
@extends('layouts.admin')

@section('admin')
    <h3>User <small> @yield('type') </small></h3>
    @yield('user')
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.user._layout')

@section('user')
    <div class="panel panel-default">
        <div class="panel-body">
            @include('admin.user.form', ['model' => $user, 'method' => 'PUT', 'url' => route('admin.user.update', ['user' => $user])])
        </div>
    </div>
@endsection

@section('type', 'Edit')

resources/views/admin/user/form.blade.php
@include('components.errors')
{{ Form::model($model,['url' => $url, 'method' => $method]) }}
<div class="form-group">
    {{ Form::label('email', 'Email') }}
    {{ Form::text('email', null, ['class' => 'form-control']) }}
</div>

<div class="form-group">
    {{ Form::label('name', 'Name') }}
    {{ Form::text('name', null, ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::checkbox('admin', null) }}
    {{ Form::label('admin', 'Admin') }}
</div>
<div class="form-group">
    {{ Form::checkbox('banned', null) }}
    {{ Form::label('banned', 'Banned') }}
</div>
<div class="form-group">
    {{ Form::submit('Save',['class' => 'btn-primary btn-block']) }}
</div>
{{ Form::close() }}

resources/views/admin/user/index.blade.php
@extends('admin.user._layout')

@section('user')
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <td>#</td>
                    <td></td>
                    <td>Name</td>
                    <td>Email</td>
                    <td class="text-center">Actions</td>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>
                            @if($user->avatar)
                                <img width="32" src="{{ $user->avatar }}" alt="{{ $user->name  }}" class="img-circle">
                            @endif
                        </td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td class="text-center">
                            <a href="{{ route('admin.user.edit', ['user' => $user]) }}"
                               class="btn btn-default btn-xs">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $users->links() }}
        </div>
    </div>
@endsection